Repository manna84/collab-sem2-project, pull requests merged in 2020-07, with the labels that each got.

#4 Mvc model
  package-lock.json
  package.json
  server.js
Labels: enhancement

#6 Mvc model
  controllers/general.js
  public/css/default.css
  public/css/style.css
  public/img/bemypet.png
  public/img/bg.png
  public/img/brown-eyes.png
  public/img/cat.png
  public/img/dog-red.png
  public/img/dog-rope.png
  public/img/jump.png
  server.js
  views/home.handlebars
  views/layouts/main.handlebars
Labels: enhancement

#10 update readme.md
  README.md
Labels: documentation

#11 Mvc model
  controllers/general.js
  public/css/default.css
  public/css/style.css
  public/img/facebook.svg
  public/img/search.svg
  public/img/snapchat.svg
  public/img/twitter.svg
  public/img/youtube.svg
  public/js/forum.js
  views/forum.handlebars
  views/layouts/main.handlebars
Labels: enhancement

#13 Mvc model
  public/css/style.css
  public/js/forum.js
  views/forum.handlebars
  views/layouts/main.handlebars
Labels: enhancement

#16 Mvc model
  public/css/style.css
  public/js/forum.js
  views/forum.handlebars
Labels: bug

#19 Log in/sign up page
  controllers/general.js
  public/css/style.css
  views/login.handlebars
  views/registration.handlebars
Labels: enhancement

#20 created counter for form submisson
  public/js/forum.js
  views/forum.handlebars
Labels: enhancement

#23 bug fixed for counter for total posts regarding empty field submission
  public/js/forum.js
Labels: bug

#25 Log in/sign up page
  README.md
  controllers/general.js
  package-lock.json
  package.json
  public/img/alarm.svg
  public/img/info.svg
  server.js
Labels: enhancement

#24 styled counter button
  public/css/style.css
  public/js/forum.js
  views/forum.handlebars
Labels: enhancement

#29 Mvc model
  README.md
  controllers/general.js
  public/css/default.css
  public/css/normalize.css
  public/css/style.css
  public/js/forum.js
  server.js
  views/forum.handlebars
  views/home.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/registration.handlebars
Labels: enhancement

#31 Mvc model
  controllers/general.js
  public/css/style.css
  public/js/forum.js
  views/forum.handlebars
  views/home.handlebars
Labels: make improvement
