Repository manna84/collab-sem2-project, pull requests merged in 2020-08, with the labels that each got.

#36 Chat App Working+Styling
  controllers/general.js
  package-lock.json
  package.json
  public/css/style.css
  public/js/chat.js
  server.js
  views/chat.handlebars
  views/layouts/main.handlebars
Labels: bug

#39 Convert css styled components
  .babelrc
  .gitignore
  controllers/general.js
  package-lock.json
  package.json
  public/css/default.css
  public/css/style.css
  public/js/forum.js
  server.js
  src/css/App.css
  src/css/Forum.css
  src/css/footer.css
  src/css/header.css
  src/css/index.css
  src/css/normalize.css
  src/img/alarm.svg
  src/img/bemypet.png
  src/img/bg.png
  src/img/brown-eyes.png
  src/img/cat.png
  src/img/dog-red.png
  src/img/dog-rope.png
  src/img/facebook.svg
  src/img/info.svg
  src/img/jump.png
  src/img/search.svg
  src/img/snapchat.svg
  src/img/twitter.svg
  src/img/youtube.svg
  src/index.html
  src/index.js
  src/js/chat.js
  src/js/components/App.js
  src/js/components/Footer.js
  src/js/components/Header.js
  src/js/components/forum.js
  views/home.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/registration.handlebars
  webpack.config.js
Labels: bug, enhancement, make improvement

#40 Header styled component
  src/css/header.css
  src/js/components/Header.js
Labels: make improvement

#41 Footer styled component
  src/css/footer.css
  src/js/components/Footer.js
Labels: make improvement
